
title: M1lachite_
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: dark
  show_excerpts: true
  social_links:
      - title: M1lachite_ repository at GitHub
        icon: github
        url: "https://github.com/M1lachite"
      - title: M1lachite_ linkedin profile
        icon: linkedin
        url: "https://www.linkedin.com/in/kristof-o/"
      - title: M1lachite_ udemy profile
        icon:  fa-puzzle
        url: "https://www.udemy.com/user/ko-256"
  hide_site_feed_link: true
